
INSERT INTO `cfops` VALUES (1, 1000, 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO ESTADO', NULL, NULL);
INSERT INTO `cfops` VALUES (2, 1100, 'COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (3, 1101, 'Compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (4, 1102, 'Compra para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (5, 1111, 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (6, 1113, 'Compra para comercialização de mercadoria recebida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (7, 1116, 'Compra para industrialização ou produção rural originada de encomenda para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (8, 1117, 'Compra para comercialização originada de encomenda para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (9, 1118, 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (10, 1120, 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', NULL, NULL);
INSERT INTO `cfops` VALUES (11, 1121, 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', NULL, NULL);
INSERT INTO `cfops` VALUES (12, 1122, 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (13, 1124, 'Industrialização efetuada por outra empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (14, 1125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', NULL, NULL);
INSERT INTO `cfops` VALUES (15, 1126, 'Compra para utilização na prestação de serviço sujeita ao ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (16, 1128, 'Compra para utilização na prestação de serviço sujeita ao ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (17, 1131, 'Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (18, 1132, 'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização.', NULL, NULL);
INSERT INTO `cfops` VALUES (19, 1135, 'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.', NULL, NULL);
INSERT INTO `cfops` VALUES (20, 1150, 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (21, 1151, 'Transferência para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (22, 1152, 'Transferência para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (23, 1153, 'Transferência de energia elétrica para distribuição', NULL, NULL);
INSERT INTO `cfops` VALUES (24, 1154, 'Transferência para utilização na prestação de serviço', NULL, NULL);
INSERT INTO `cfops` VALUES (25, 1159, 'Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (26, 1200, 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (27, 1201, 'Devolução de venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (28, 1202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 1.503, 1.504, 1.505 e 1.506', NULL, NULL);
INSERT INTO `cfops` VALUES (29, 1203, 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (30, 1204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (31, 1205, 'Anulação de valor relativo à prestação de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (32, 1206, 'Anulação de valor relativo à prestação de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (33, 1207, 'Anulação de valor relativo à venda de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (34, 1208, 'Devolução de produção do estabelecimento, remetida em transferência', NULL, NULL);
INSERT INTO `cfops` VALUES (35, 1209, 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', NULL, NULL);
INSERT INTO `cfops` VALUES (36, 1212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (37, 1213, 'Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (38, 1214, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (39, 1215, 'Devolução de fornecimento de produção do estabelecimento de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (40, 1216, 'Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (41, 1250, 'COMPRAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (42, 1251, 'Compra de energia elétrica para distribuição ou comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (43, 1252, 'Compra de energia elétrica por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (44, 1253, 'Compra de energia elétrica por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (45, 1254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (46, 1255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (47, 1256, 'Compra de energia elétrica por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (48, 1257, 'Compra de energia elétrica para consumo por demanda contratada', NULL, NULL);
INSERT INTO `cfops` VALUES (49, 1300, 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (50, 1301, 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (51, 1302, 'Aquisição de serviço de comunicação por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (52, 1303, 'Aquisição de serviço de comunicação por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (53, 1304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (54, 1305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (55, 1306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (56, 1350, 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (57, 1351, 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (58, 1352, 'Aquisição de serviço de transporte por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (59, 1353, 'Aquisição de serviço de transporte por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (60, 1354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (61, 1355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (62, 1356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (63, 1360, 'Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (64, 1400, 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA', NULL, NULL);
INSERT INTO `cfops` VALUES (65, 1401, 'Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (66, 1403, 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (67, 1406, 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (68, 1407, 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (69, 1408, 'Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (70, 1409, 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (71, 1410, 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (72, 1411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (73, 1414, 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (74, 1415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (75, 1450, 'SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL', NULL, NULL);
INSERT INTO `cfops` VALUES (76, 1451, 'Entrada de animal - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (77, 1452, 'Entrada de insumo - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (78, 1453, 'Retorno do animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (79, 1454, 'Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (80, 1455, 'Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (81, 1456, 'Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (82, 1500, 'ENTRADAS DE MERCADORIAS REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES', NULL, NULL);
INSERT INTO `cfops` VALUES (83, 1501, 'Entrada de mercadoria recebida com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (84, 1503, 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (85, 1504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (86, 1505, 'Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (87, 1506, 'Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (88, 1550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO', NULL, NULL);
INSERT INTO `cfops` VALUES (89, 1551, 'Compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (90, 1552, 'Transferência de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (91, 1553, 'Devolução de venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (92, 1554, 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (93, 1555, 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (94, 1556, 'Compra de material para uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (95, 1557, 'Transferência de material para uso ou consumo ', NULL, NULL);
INSERT INTO `cfops` VALUES (96, 1600, 'CRÉDITOS E RESSARCIMENTOS DE ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (97, 1601, 'Recebimento, por transferência, de crédito de ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (98, 1602, 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (99, 1603, 'Ressarcimento de ICMS retido por substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (100, 1604, 'Lançamento do crédito relativo à compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (101, 1605, 'Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (102, 1650, 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (103, 1651, 'Compra de combustível ou lubrificante para industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (104, 1652, 'Compra de combustível ou lubrificante para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (105, 1653, 'Compra de combustível ou lubrificante por consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (106, 1657, 'Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (107, 1658, 'Transferência de combustível e lubrificante para industrialização', NULL, NULL);
INSERT INTO `cfops` VALUES (108, 1659, 'Transferência de combustível e lubrificante para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (109, 1660, 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (110, 1661, 'Devolução de venda de combustível ou lubrificante destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (111, 1662, 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (112, 1663, 'Entrada de combustível ou lubrificante para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (113, 1664, 'Retorno de combustível ou lubrificante remetido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (114, 1900, 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (115, 1901, 'Entrada para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (116, 1902, 'Retorno de mercadoria remetida para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (117, 1903, 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', NULL, NULL);
INSERT INTO `cfops` VALUES (118, 1904, 'Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 1.202, 1.503, 1.504, 1.505 e 1.506', NULL, NULL);
INSERT INTO `cfops` VALUES (119, 1905, 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (120, 1906, 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (121, 1907, 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (122, 1908, 'Entrada de bem por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (123, 1909, 'Retorno de bem remetido por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (124, 1910, 'Entrada de bonificação, doação ou brinde', NULL, NULL);
INSERT INTO `cfops` VALUES (125, 1911, 'Entrada de amostra grátis', NULL, NULL);
INSERT INTO `cfops` VALUES (126, 1912, 'Entrada de mercadoria ou bem recebido para demonstração ou mostruário', NULL, NULL);
INSERT INTO `cfops` VALUES (127, 1913, 'Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento', NULL, NULL);
INSERT INTO `cfops` VALUES (128, 1914, 'Retorno de mercadoria ou bem remetido para exposição ou feira', NULL, NULL);
INSERT INTO `cfops` VALUES (129, 1915, 'Entrada de mercadoria ou bem recebido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (130, 1916, 'Retorno de mercadoria ou bem remetido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (131, 1917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (132, 1918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (133, 1919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (134, 1920, 'Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (135, 1921, 'Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (136, 1922, 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (137, 1923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (138, 1924, 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (139, 1925, 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (140, 1926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', NULL, NULL);
INSERT INTO `cfops` VALUES (141, 1929, 'LANÇAMENTO REGISTRADO EM EQUIPAMENTO EMI', NULL, NULL);
INSERT INTO `cfops` VALUES (142, 1931, 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado p', NULL, NULL);
INSERT INTO `cfops` VALUES (143, 1932, 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador', NULL, NULL);
INSERT INTO `cfops` VALUES (144, 1933, 'Aquisição de serviço tributado pelo ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (145, 1934, 'Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (146, 1949, 'Outra entrada de mercadoria ou prestação de serviço não especificada', NULL, NULL);
INSERT INTO `cfops` VALUES (147, 2000, 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DE OUTROS ESTADOS', NULL, NULL);
INSERT INTO `cfops` VALUES (148, 2100, 'COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (149, 2101, 'Compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (150, 2102, 'Compra para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (151, 2111, 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (152, 2113, 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (153, 2116, 'Compra para industrialização ou produção rural originada de encomenda para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (154, 2117, 'Compra para comercialização originada de encomenda para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (155, 2118, 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (156, 2120, 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', NULL, NULL);
INSERT INTO `cfops` VALUES (157, 2121, 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', NULL, NULL);
INSERT INTO `cfops` VALUES (158, 2122, 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (159, 2124, 'Industrialização efetuada por outra empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (160, 2125, 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria', NULL, NULL);
INSERT INTO `cfops` VALUES (161, 2126, 'Compra para utilização na prestação de serviço sujeita ao ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (162, 2128, 'Compra para utilização na prestação de serviço sujeita ao ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (163, 2131, 'Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (164, 2132, 'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização.', NULL, NULL);
INSERT INTO `cfops` VALUES (165, 2135, 'Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.', NULL, NULL);
INSERT INTO `cfops` VALUES (166, 2150, 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (167, 2151, 'Transferência para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (168, 2152, 'Transferência para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (169, 2153, 'Transferência de energia elétrica para distribuição', NULL, NULL);
INSERT INTO `cfops` VALUES (170, 2154, 'Transferência para utilização na prestação de serviço', NULL, NULL);
INSERT INTO `cfops` VALUES (171, 2159, 'Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (172, 2200, 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (173, 2201, 'Devolução de venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (174, 2202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 2.503, 2.504, 2.505 e 2.506', NULL, NULL);
INSERT INTO `cfops` VALUES (175, 2203, 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (176, 2204, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (177, 2205, 'Anulação de valor relativo à prestação de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (178, 2206, 'Anulação de valor relativo à prestação de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (179, 2207, 'Anulação de valor relativo à venda de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (180, 2208, 'Devolução de produção do estabelecimento, remetida em transferência', NULL, NULL);
INSERT INTO `cfops` VALUES (181, 2209, 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', NULL, NULL);
INSERT INTO `cfops` VALUES (182, 2212, 'Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (183, 2213, 'Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (184, 2214, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (185, 2215, 'Devolução de fornecimento de produção do estabelecimento de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (186, 2216, 'Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (187, 2250, 'COMPRAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (188, 2251, 'Compra de energia elétrica para distribuição ou comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (189, 2252, 'Compra de energia elétrica por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (190, 2253, 'Compra de energia elétrica por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (191, 2254, 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (192, 2255, 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (193, 2256, 'Compra de energia elétrica por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (194, 2257, 'Compra de energia elétrica para consumo por demanda contratada', NULL, NULL);
INSERT INTO `cfops` VALUES (195, 2300, 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (196, 2301, 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (197, 2302, 'Aquisição de serviço de comunicação por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (198, 2303, 'Aquisição de serviço de comunicação por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (199, 2304, 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (200, 2305, 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (201, 2306, 'Aquisição de serviço de comunicação por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (202, 2350, 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (203, 2351, 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (204, 2352, 'Aquisição de serviço de transporte por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (205, 2353, 'Aquisição de serviço de transporte por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (206, 2354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (207, 2355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (208, 2356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (209, 2400, 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA', NULL, NULL);
INSERT INTO `cfops` VALUES (210, 2401, 'Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (211, 2403, 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (212, 2406, 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (213, 2407, 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (214, 2408, 'Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (215, 2409, 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (216, 2410, 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (217, 2411, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (218, 2414, 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (219, 2415, 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (220, 2450, 'SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL', NULL, NULL);
INSERT INTO `cfops` VALUES (221, 2451, 'Entrada de animal - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (222, 2452, 'Entrada de insumo - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (223, 2453, 'Retorno do animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (224, 2454, 'Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (225, 2455, 'Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (226, 2456, 'Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (227, 2500, 'ENTRADAS DE MERCADORIAS REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES', NULL, NULL);
INSERT INTO `cfops` VALUES (228, 2501, 'Entrada de mercadoria recebida com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (229, 2503, 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (230, 2504, 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (231, 2505, 'Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (232, 2506, 'Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (233, 2550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO ', NULL, NULL);
INSERT INTO `cfops` VALUES (234, 2551, 'Compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (235, 2552, 'Transferência de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (236, 2553, 'Devolução de venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (237, 2554, 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (238, 2555, 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (239, 2556, 'Compra de material para uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (240, 2557, 'Transferência de material para uso ou consumo ', NULL, NULL);
INSERT INTO `cfops` VALUES (241, 2600, 'CRÉDITOS E RESSARCIMENTOS DE ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (242, 2603, 'Ressarcimento de ICMS retido por substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (243, 2650, 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (244, 2651, 'Compra de combustível ou lubrificante para industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (245, 2652, 'Compra de combustível ou lubrificante para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (246, 2653, 'Compra de combustível ou lubrificante por consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (247, 2657, 'Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (248, 2658, 'Transferência de combustível e lubrificante para industrialização', NULL, NULL);
INSERT INTO `cfops` VALUES (249, 2659, 'Transferência de combustível e lubrificante para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (250, 2660, 'Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (251, 2661, 'Devolução de venda de combustível ou lubrificante destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (252, 2662, 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (253, 2663, 'Entrada de combustível ou lubrificante para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (254, 2664, 'Retorno de combustível ou lubrificante remetido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (255, 2900, 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (256, 2901, 'Entrada para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (257, 2902, 'Retorno de mercadoria remetida para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (258, 2903, 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', NULL, NULL);
INSERT INTO `cfops` VALUES (259, 2904, 'Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 2.202, 2.503, 2.504, 2.505 e 2.506', NULL, NULL);
INSERT INTO `cfops` VALUES (260, 2905, 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (261, 2906, 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (262, 2907, 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (263, 2908, 'Entrada de bem por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (264, 2909, 'Retorno de bem remetido por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (265, 2910, 'Entrada de bonificação, doação ou brinde', NULL, NULL);
INSERT INTO `cfops` VALUES (266, 2911, 'Entrada de amostra grátis', NULL, NULL);
INSERT INTO `cfops` VALUES (267, 2912, 'Entrada de mercadoria ou bem recebido para demonstração ou mostruário', NULL, NULL);
INSERT INTO `cfops` VALUES (268, 2913, 'Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento', NULL, NULL);
INSERT INTO `cfops` VALUES (269, 2914, 'Retorno de mercadoria ou bem remetido para exposição ou feira', NULL, NULL);
INSERT INTO `cfops` VALUES (270, 2915, 'Entrada de mercadoria ou bem recebido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (271, 2916, 'Retorno de mercadoria ou bem remetido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (272, 2917, 'Entrada de mercadoria recebida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (273, 2918, 'Devolução de mercadoria remetida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (274, 2919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (275, 2920, 'Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (276, 2921, 'Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (277, 2922, 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', NULL, NULL);
INSERT INTO `cfops` VALUES (278, 2923, 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (279, 2924, 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (280, 2925, 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (281, 2931, 'Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado p', NULL, NULL);
INSERT INTO `cfops` VALUES (282, 2932, 'Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador', NULL, NULL);
INSERT INTO `cfops` VALUES (283, 2933, 'Aquisição de serviço tributado pelo ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (284, 2934, 'Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (285, 2949, 'Outra entrada de mercadoria ou prestação de serviço não especificado', NULL, NULL);
INSERT INTO `cfops` VALUES (286, 3000, 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO EXTERIOR', NULL, NULL);
INSERT INTO `cfops` VALUES (287, 3100, 'COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (288, 3101, 'Compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (289, 3102, 'Compra para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (290, 3126, 'Compra para utilização na prestação de serviço sujeita ao ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (291, 3127, 'Compra para industrialização sob o regime de \Zdrawback\Z', NULL, NULL);
INSERT INTO `cfops` VALUES (292, 3128, 'Compra para utilização na prestação de serviço sujeita ao ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (293, 3129, 'Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (294, 3200, 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (295, 3201, 'Devolução de venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (296, 3202, 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (297, 3205, 'Anulação de valor relativo à prestação de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (298, 3206, 'Anulação de valor relativo à prestação de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (299, 3207, 'Anulação de valor relativo à venda de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (300, 3211, 'Devolução de venda de produção do estabelecimento sob o regime de \Zdrawback\Z', NULL, NULL);
INSERT INTO `cfops` VALUES (301, 3212, 'Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (302, 3250, 'COMPRAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (303, 3251, 'Compra de energia elétrica para distribuição ou comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (304, 3300, 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (305, 3301, 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (306, 3350, 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (307, 3351, 'Aquisição de serviço de transporte para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (308, 3352, 'Aquisição de serviço de transporte por estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (309, 3353, 'Aquisição de serviço de transporte por estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (310, 3354, 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (311, 3355, 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (312, 3356, 'Aquisição de serviço de transporte por estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (313, 3500, 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES', NULL, NULL);
INSERT INTO `cfops` VALUES (314, 3503, 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (315, 3550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO ', NULL, NULL);
INSERT INTO `cfops` VALUES (316, 3551, 'Compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (317, 3552, 'Entrada de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior', NULL, NULL);
INSERT INTO `cfops` VALUES (318, 3553, 'Devolução de venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (319, 3556, 'Compra de material para uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (320, 3650, 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (321, 3651, 'Compra de combustível ou lubrificante para industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (322, 3652, 'Compra de combustível ou lubrificante para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (323, 3653, 'Compra de combustível ou lubrificante por consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (324, 3667, 'Entrada de combustível ou lubrificante para consumo final, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior', NULL, NULL);
INSERT INTO `cfops` VALUES (325, 3900, 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (326, 3930, 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária', NULL, NULL);
INSERT INTO `cfops` VALUES (327, 3949, 'Outra entrada de mercadoria ou prestação de serviço não especificado', NULL, NULL);
INSERT INTO `cfops` VALUES (328, 5000, 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O ESTADO', NULL, NULL);
INSERT INTO `cfops` VALUES (329, 5100, 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS', NULL, NULL);
INSERT INTO `cfops` VALUES (330, 5101, 'Venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (331, 5102, 'Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505', NULL, NULL);
INSERT INTO `cfops` VALUES (332, 5103, 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (333, 5104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (334, 5105, 'Venda de produção do estabelecimento que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (335, 5106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (336, 5107, 'Venda de produção de estabelecimento, destinada a não contribuite', NULL, NULL);
INSERT INTO `cfops` VALUES (337, 5109, 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (338, 5110, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (339, 5111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (340, 5112, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (341, 5113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (342, 5114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (343, 5115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (344, 5116, 'Venda de produção do estabelecimento originada de encomenda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (345, 5117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (346, 5118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (347, 5119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem ', NULL, NULL);
INSERT INTO `cfops` VALUES (348, 5120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (349, 5122, 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (350, 5123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (351, 5124, 'Industrialização efetuada para outra empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (352, 5125, 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', NULL, NULL);
INSERT INTO `cfops` VALUES (353, 5129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (354, 5131, 'Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (355, 5132, 'Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (356, 5150, 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS', NULL, NULL);
INSERT INTO `cfops` VALUES (357, 5151, 'Transferência de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (358, 5152, 'Transferência de mercadoria adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (359, 5153, 'Transferência de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (360, 5155, 'Transferência de produção do estabelecimento, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (361, 5156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (362, 5159, 'Fornecimento de produção do estabelecimento de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (363, 5160, 'Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (364, 5200, 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (365, 5201, 'Devolução de compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (366, 5202, 'Devolução de compra para comercialização, ou qualquer devolução de mercadorias efetuada pelo MEI com exceção das classificadas no código 5.503', NULL, NULL);
INSERT INTO `cfops` VALUES (367, 5205, 'Anulação de valor relativo a aquisição de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (368, 5206, 'Anulação de valor relativo a aquisição de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (369, 5207, 'Anulação de valor relativo à compra de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (370, 5208, 'Devolução de mercadoria recebida em transferência para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (371, 5209, 'Devolução de mercadoria recebida em transferência para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (372, 5210, 'Devolução de compra para utilização na prestação de serviço', NULL, NULL);
INSERT INTO `cfops` VALUES (373, 5213, 'Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (374, 5214, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (375, 5215, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para industrialização', NULL, NULL);
INSERT INTO `cfops` VALUES (376, 5216, 'Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (377, 5250, 'VENDAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (378, 5251, 'Venda de energia elétrica para distribuição ou comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (379, 5252, 'Venda de energia elétrica para estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (380, 5253, 'Venda de energia elétrica para estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (381, 5254, 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (382, 5255, 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (383, 5256, 'Venda de energia elétrica para estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (384, 5257, 'Venda de energia elétrica para consumo por demanda contratada', NULL, NULL);
INSERT INTO `cfops` VALUES (385, 5258, 'Venda de energia elétrica a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (386, 5300, 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (387, 5301, 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (388, 5302, 'Prestação de serviço de comunicação a estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (389, 5303, 'Prestação de serviço de comunicação a estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (390, 5304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (391, 5305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (392, 5306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (393, 5307, 'Prestação de serviço de comunicação a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (394, 5350, 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (395, 5351, 'Prestação de serviço de transporte para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (396, 5352, 'Prestação de serviço de transporte a estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (397, 5353, 'Prestação de serviço de transporte a estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (398, 5354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (399, 5355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (400, 5356, 'Prestação de serviço de transporte a estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (401, 5357, 'Prestação de serviço de transporte a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (402, 5359, 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal', NULL, NULL);
INSERT INTO `cfops` VALUES (403, 5360, 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (404, 5400, 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA', NULL, NULL);
INSERT INTO `cfops` VALUES (405, 5401, 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', NULL, NULL);
INSERT INTO `cfops` VALUES (406, 5402, 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', NULL, NULL);
INSERT INTO `cfops` VALUES (407, 5403, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto ', NULL, NULL);
INSERT INTO `cfops` VALUES (408, 5405, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído', NULL, NULL);
INSERT INTO `cfops` VALUES (409, 5408, 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (410, 5409, 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (411, 5410, 'Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (412, 5411, 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (413, 5412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (414, 5413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (415, 5414, 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (416, 5415, 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (417, 5450, 'SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL', NULL, NULL);
INSERT INTO `cfops` VALUES (418, 5451, 'Remessa de animal - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (419, 5452, 'Remessa de insumo - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (420, 5453, 'Retorno de animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (421, 5454, 'Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (422, 5455, 'Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (423, 5456, 'Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (424, 5500, 'REMESSAS PARA FORMAÇÃO DE LOTE E COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES', NULL, NULL);
INSERT INTO `cfops` VALUES (425, 5501, 'Remessa de produção do estabelecimento, com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (426, 5502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (427, 5503, 'Devolução de mercadoria recebida com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (428, 5504, 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (429, 5505, 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (430, 5550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO ', NULL, NULL);
INSERT INTO `cfops` VALUES (431, 5551, 'Venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (432, 5552, 'Transferência de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (433, 5553, 'Devolução de compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (434, 5554, 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (435, 5555, 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (436, 5556, 'Devolução de compra de material de uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (437, 5557, 'Transferência de material de uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (438, 5600, 'CRÉDITOS E RESSARCIMENTOS DE ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (439, 5601, 'Transferência de crédito de ICMS acumulado', NULL, NULL);
INSERT INTO `cfops` VALUES (440, 5602, 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (441, 5603, 'Ressarcimento de ICMS retido por substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (442, 5605, 'Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (443, 5606, 'Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais', NULL, NULL);
INSERT INTO `cfops` VALUES (444, 5650, 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (445, 5651, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (446, 5652, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (447, 5653, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (448, 5654, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (449, 5655, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (450, 5656, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (451, 5657, 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (452, 5658, 'Transferência de combustível ou lubrificante de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (453, 5659, 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', NULL, NULL);
INSERT INTO `cfops` VALUES (454, 5660, 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (455, 5661, 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (456, 5662, 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (457, 5663, 'Remessa para armazenagem de combustível ou lubrificante', NULL, NULL);
INSERT INTO `cfops` VALUES (458, 5664, 'Retorno de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (459, 5665, 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (460, 5666, 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (461, 5667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação', NULL, NULL);
INSERT INTO `cfops` VALUES (462, 5900, 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (463, 5901, 'Remessa para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (464, 5902, 'Retorno de mercadoria utilizada na industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (465, 5903, 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', NULL, NULL);
INSERT INTO `cfops` VALUES (466, 5904, 'Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 5.502 e 5.505', NULL, NULL);
INSERT INTO `cfops` VALUES (467, 5905, 'Remessa para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (468, 5906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (469, 5907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (470, 5908, 'Remessa de bem por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (471, 5909, 'Retorno de bem recebido por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (472, 5910, 'Remessa em bonificação, doação ou brinde', NULL, NULL);
INSERT INTO `cfops` VALUES (473, 5911, 'Remessa de amostra grátis', NULL, NULL);
INSERT INTO `cfops` VALUES (474, 5912, 'Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento', NULL, NULL);
INSERT INTO `cfops` VALUES (475, 5913, 'Retorno de mercadoria ou bem recebido para demonstração ou mostruário', NULL, NULL);
INSERT INTO `cfops` VALUES (476, 5914, 'Remessa de mercadoria ou bem para exposição ou feira', NULL, NULL);
INSERT INTO `cfops` VALUES (477, 5915, 'Remessa de mercadoria ou bem para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (478, 5916, 'Retorno de mercadoria ou bem recebido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (479, 5917, 'Remessa de mercadoria em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (480, 5918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (481, 5919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (482, 5920, 'Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (483, 5921, 'Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (484, 5922, 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (485, 5923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', NULL, NULL);
INSERT INTO `cfops` VALUES (486, 5924, 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (487, 5925, 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (488, 5926, 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', NULL, NULL);
INSERT INTO `cfops` VALUES (489, 5927, 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', NULL, NULL);
INSERT INTO `cfops` VALUES (490, 5928, 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (491, 5929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acorbertada por documento fiscal do varejo', NULL, NULL);
INSERT INTO `cfops` VALUES (492, 5931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por t', NULL, NULL);
INSERT INTO `cfops` VALUES (493, 5932, 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', NULL, NULL);
INSERT INTO `cfops` VALUES (494, 5933, 'Prestação de serviço tributado pelo ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (495, 5934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', NULL, NULL);
INSERT INTO `cfops` VALUES (496, 5949, 'Outra saída de mercadoria ou prestação de serviço não especificado', NULL, NULL);
INSERT INTO `cfops` VALUES (497, 5953, 'SERVIÇOS PRESTADOS ', NULL, NULL);
INSERT INTO `cfops` VALUES (498, 6000, 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA OUTROS ESTADOS', NULL, NULL);
INSERT INTO `cfops` VALUES (499, 6100, 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS', NULL, NULL);
INSERT INTO `cfops` VALUES (500, 6101, 'Venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (501, 6102, 'Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 6.501, 6.502, 6.504 e 6.505', NULL, NULL);
INSERT INTO `cfops` VALUES (502, 6103, 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (503, 6104, 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (504, 6105, 'Venda de produção do estabelecimento que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (505, 6106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (506, 6107, 'Venda de produção do estabelecimento, destinada a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (507, 6108, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (508, 6109, 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (509, 6110, 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', NULL, NULL);
INSERT INTO `cfops` VALUES (510, 6111, 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (511, 6112, 'Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (512, 6113, 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (513, 6114, 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (514, 6115, 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', NULL, NULL);
INSERT INTO `cfops` VALUES (515, 6116, 'Venda de produção do estabelecimento originada de encomenda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (516, 6117, 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (517, 6118, 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (518, 6119, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem ', NULL, NULL);
INSERT INTO `cfops` VALUES (519, 6120, 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', NULL, NULL);
INSERT INTO `cfops` VALUES (520, 6122, 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (521, 6123, 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (522, 6124, 'Industrialização efetuada para outra empresa', NULL, NULL);
INSERT INTO `cfops` VALUES (523, 6125, 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria', NULL, NULL);
INSERT INTO `cfops` VALUES (524, 6129, 'Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (525, 6131, 'Remessa de produção de estabelecimento, com previsão de posterior ajuste ou fixação de preço de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (526, 6132, 'Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (527, 6150, 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS', NULL, NULL);
INSERT INTO `cfops` VALUES (528, 6151, 'Transferência de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (529, 6152, 'Transferência de mercadoria adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (530, 6153, 'Transferência de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (531, 6155, 'Transferência de produção do estabelecimento, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (532, 6156, 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (533, 6159, 'Fornecimento de produção do estabelecimento de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (534, 6160, 'Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (535, 6200, 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (536, 6201, 'Devolução de compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (537, 6202, 'Devolução de compra para comercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 6.503', NULL, NULL);
INSERT INTO `cfops` VALUES (538, 6205, 'Anulação de valor relativo a aquisição de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (539, 6206, 'Anulação de valor relativo a aquisição de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (540, 6207, 'Anulação de valor relativo à compra de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (541, 6208, 'Devolução de mercadoria recebida em transferência para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (542, 6209, 'Devolução de mercadoria recebida em transferência para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (543, 6210, 'Devolução de compra para utilização na prestação de serviço', NULL, NULL);
INSERT INTO `cfops` VALUES (544, 6213, 'Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.', NULL, NULL);
INSERT INTO `cfops` VALUES (545, 6214, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (546, 6215, 'Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para industrialização', NULL, NULL);
INSERT INTO `cfops` VALUES (547, 6216, 'Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo', NULL, NULL);
INSERT INTO `cfops` VALUES (548, 6250, 'VENDAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (549, 6251, 'Venda de energia elétrica para distribuição ou comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (550, 6252, 'Venda de energia elétrica para estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (551, 6253, 'Venda de energia elétrica para estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (552, 6254, 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (553, 6255, 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (554, 6256, 'Venda de energia elétrica para estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (555, 6257, 'Venda de energia elétrica para consumo por demanda contratada', NULL, NULL);
INSERT INTO `cfops` VALUES (556, 6258, 'Venda de energia elétrica a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (557, 6300, 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (558, 6301, 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (559, 6302, 'Prestação de serviço de comunicação a estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (560, 6303, 'Prestação de serviço de comunicação a estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (561, 6304, 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (562, 6305, 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (563, 6306, 'Prestação de serviço de comunicação a estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (564, 6307, 'Prestação de serviço de comunicação a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (565, 6350, 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (566, 6351, 'Prestação de serviço de transporte para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (567, 6352, 'Prestação de serviço de transporte a estabelecimento industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (568, 6353, 'Prestação de serviço de transporte a estabelecimento comercial', NULL, NULL);
INSERT INTO `cfops` VALUES (569, 6354, 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação ', NULL, NULL);
INSERT INTO `cfops` VALUES (570, 6355, 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (571, 6356, 'Prestação de serviço de transporte a estabelecimento de produtor rural', NULL, NULL);
INSERT INTO `cfops` VALUES (572, 6357, 'Prestação de serviço de transporte a não contribuinte', NULL, NULL);
INSERT INTO `cfops` VALUES (573, 6359, 'Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal', NULL, NULL);
INSERT INTO `cfops` VALUES (574, 6360, 'Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (575, 6400, 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA', NULL, NULL);
INSERT INTO `cfops` VALUES (576, 6401, 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', NULL, NULL);
INSERT INTO `cfops` VALUES (577, 6402, 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto', NULL, NULL);
INSERT INTO `cfops` VALUES (578, 6403, 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto ', NULL, NULL);
INSERT INTO `cfops` VALUES (579, 6404, 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', NULL, NULL);
INSERT INTO `cfops` VALUES (580, 6408, 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (581, 6409, 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (582, 6410, 'Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (583, 6411, 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (584, 6412, 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (585, 6413, 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (586, 6414, 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (587, 6415, 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (588, 6450, 'SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL', NULL, NULL);
INSERT INTO `cfops` VALUES (589, 6451, 'Remessa de animal - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (590, 6452, 'Remessa de insumo - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (591, 6453, 'Retorno de animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (592, 6454, 'Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (593, 6455, 'Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (594, 6456, 'Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural', NULL, NULL);
INSERT INTO `cfops` VALUES (595, 6500, 'REMESSAS PARA FORMAÇÃO DE LOTE E COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES', NULL, NULL);
INSERT INTO `cfops` VALUES (596, 6501, 'Remessa de produção do estabelecimento, com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (597, 6502, 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (598, 6503, 'Devolução de mercadoria recebida com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (599, 6504, 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (600, 6505, 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (601, 6550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO ', NULL, NULL);
INSERT INTO `cfops` VALUES (602, 6551, 'Venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (603, 6552, 'Transferência de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (604, 6553, 'Devolução de compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (605, 6554, 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (606, 6555, 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (607, 6556, 'Devolução de compra de material de uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (608, 6557, 'Transferência de material de uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (609, 6600, 'CRÉDITOS E RESSARCIMENTOS DE ICMS', NULL, NULL);
INSERT INTO `cfops` VALUES (610, 6603, 'Ressarcimento de ICMS retido por substituição tributária', NULL, NULL);
INSERT INTO `cfops` VALUES (611, 6650, 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (612, 6651, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (613, 6652, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (614, 6653, 'Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (615, 6654, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (616, 6655, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (617, 6656, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (618, 6657, 'Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (619, 6658, 'Transferência de combustível ou lubrificante de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (620, 6659, 'Transferência de combustível ou lubrificante adquirido ou recebido de terceiro', NULL, NULL);
INSERT INTO `cfops` VALUES (621, 6660, 'Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente', NULL, NULL);
INSERT INTO `cfops` VALUES (622, 6661, 'Devolução de compra de combustível ou lubrificante adquirido para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (623, 6662, 'Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (624, 6663, 'Remessa para armazenagem de combustível ou lubrificante', NULL, NULL);
INSERT INTO `cfops` VALUES (625, 6664, 'Retorno de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (626, 6665, 'Retorno simbólico de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (627, 6666, 'Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem', NULL, NULL);
INSERT INTO `cfops` VALUES (628, 6667, 'Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (629, 6900, 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (630, 6901, 'Remessa para industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (631, 6902, 'Retorno de mercadoria utilizada na industrialização por encomenda', NULL, NULL);
INSERT INTO `cfops` VALUES (632, 6903, 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', NULL, NULL);
INSERT INTO `cfops` VALUES (633, 6904, 'Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 6.502 e 6.505', NULL, NULL);
INSERT INTO `cfops` VALUES (634, 6905, 'Remessa para depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (635, 6906, 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (636, 6907, 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', NULL, NULL);
INSERT INTO `cfops` VALUES (637, 6908, 'Remessa de bem por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (638, 6909, 'Retorno de bem recebido por conta de contrato de comodato ou locação', NULL, NULL);
INSERT INTO `cfops` VALUES (639, 6910, 'Remessa em bonificação, doação ou brinde', NULL, NULL);
INSERT INTO `cfops` VALUES (640, 6911, 'Remessa de amostra grátis', NULL, NULL);
INSERT INTO `cfops` VALUES (641, 6912, 'Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento', NULL, NULL);
INSERT INTO `cfops` VALUES (642, 6913, 'Retorno de mercadoria ou bem recebido para demonstração ou mostruário', NULL, NULL);
INSERT INTO `cfops` VALUES (643, 6914, 'Remessa de mercadoria ou bem para exposição ou feira', NULL, NULL);
INSERT INTO `cfops` VALUES (644, 6915, 'Remessa de mercadoria ou bem para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (645, 6916, 'Retorno de mercadoria ou bem recebido para conserto ou reparo', NULL, NULL);
INSERT INTO `cfops` VALUES (646, 6917, 'Remessa de mercadoria em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (647, 6918, 'Devolução de mercadoria recebida em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (648, 6919, 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', NULL, NULL);
INSERT INTO `cfops` VALUES (649, 6920, 'Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (650, 6921, 'Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados', NULL, NULL);
INSERT INTO `cfops` VALUES (651, 6922, 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', NULL, NULL);
INSERT INTO `cfops` VALUES (652, 6923, 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', NULL, NULL);
INSERT INTO `cfops` VALUES (653, 6924, 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (654, 6925, 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente', NULL, NULL);
INSERT INTO `cfops` VALUES (655, 6929, 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF', NULL, NULL);
INSERT INTO `cfops` VALUES (656, 6931, 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por t', NULL, NULL);
INSERT INTO `cfops` VALUES (657, 6932, 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador', NULL, NULL);
INSERT INTO `cfops` VALUES (658, 6933, 'Prestação de serviço tributado pelo ISSQN', NULL, NULL);
INSERT INTO `cfops` VALUES (659, 6934, 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', NULL, NULL);
INSERT INTO `cfops` VALUES (660, 6949, 'Outra saída de mercadoria ou prestação de serviço não especificado', NULL, NULL);
INSERT INTO `cfops` VALUES (661, 7000, 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O EXTERIOR', NULL, NULL);
INSERT INTO `cfops` VALUES (662, 7100, 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS', NULL, NULL);
INSERT INTO `cfops` VALUES (663, 7101, 'Venda de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (664, 7102, 'Venda de mercadoria adquirida ou recebida de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (665, 7105, 'Venda de produção do estabelecimento, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (666, 7106, 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar', NULL, NULL);
INSERT INTO `cfops` VALUES (667, 7127, 'Venda de produção do estabelecimento sob o regime de \Zdrawback\Z', NULL, NULL);
INSERT INTO `cfops` VALUES (668, 7129, 'Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (669, 7200, 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES', NULL, NULL);
INSERT INTO `cfops` VALUES (670, 7201, 'Devolução de compra para industrialização ou produção rural', NULL, NULL);
INSERT INTO `cfops` VALUES (671, 7202, 'Devolução de compra para comercialização', NULL, NULL);
INSERT INTO `cfops` VALUES (672, 7205, 'Anulação de valor relativo à aquisição de serviço de comunicação', NULL, NULL);
INSERT INTO `cfops` VALUES (673, 7206, 'Anulação de valor relativo a aquisição de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (674, 7207, 'Anulação de valor relativo à compra de energia elétrica', NULL, NULL);
INSERT INTO `cfops` VALUES (675, 7210, 'Devolução de compra para utilização na prestação de serviço', NULL, NULL);
INSERT INTO `cfops` VALUES (676, 7211, 'Devolução de compras para industrialização sob o regime de drawback\Z', NULL, NULL);
INSERT INTO `cfops` VALUES (677, 7212, 'Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)', NULL, NULL);
INSERT INTO `cfops` VALUES (678, 7250, 'VENDAS DE ENERGIA ELÉTRICA', NULL, NULL);
INSERT INTO `cfops` VALUES (679, 7251, 'Venda de energia elétrica para o exterior', NULL, NULL);
INSERT INTO `cfops` VALUES (680, 7300, 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO', NULL, NULL);
INSERT INTO `cfops` VALUES (681, 7301, 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', NULL, NULL);
INSERT INTO `cfops` VALUES (682, 7350, 'PRESTAÇÕES DE SERVIÇO DE TRANSPORTE', NULL, NULL);
INSERT INTO `cfops` VALUES (683, 7358, 'Prestação de serviço de transporte', NULL, NULL);
INSERT INTO `cfops` VALUES (684, 7500, 'EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO ', NULL, NULL);
INSERT INTO `cfops` VALUES (685, 7501, 'Exportação de mercadorias recebidas com fim específico de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (686, 7504, 'Exportação de mercadoria que foi objeto de formação de lote de exportação', NULL, NULL);
INSERT INTO `cfops` VALUES (687, 7550, 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO ', NULL, NULL);
INSERT INTO `cfops` VALUES (688, 7551, 'Venda de bem do ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (689, 7552, 'Saída de produtos destinados ao uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior', NULL, NULL);
INSERT INTO `cfops` VALUES (690, 7553, 'Devolução de compra de bem para o ativo imobilizado', NULL, NULL);
INSERT INTO `cfops` VALUES (691, 7556, 'Devolução de compra de material de uso ou consumo', NULL, NULL);
INSERT INTO `cfops` VALUES (692, 7650, 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES', NULL, NULL);
INSERT INTO `cfops` VALUES (693, 7651, 'Venda de combustível ou lubrificante de produção do estabelecimento', NULL, NULL);
INSERT INTO `cfops` VALUES (694, 7654, 'Venda de combustível ou lubrificante adquirido ou recebido de terceiros', NULL, NULL);
INSERT INTO `cfops` VALUES (695, 7667, 'Venda de combustível ou lubrificante a consumidor ou usuário final', NULL, NULL);
INSERT INTO `cfops` VALUES (696, 7900, 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS', NULL, NULL);
INSERT INTO `cfops` VALUES (697, 7930, 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária', NULL, NULL);
INSERT INTO `cfops` VALUES (698, 7949, 'Outra saída de mercadoria ou prestação de serviço não especificado', NULL, NULL);
INSERT INTO `cfops` VALUES (699, 7950, 'ENTRADAS DE MERCADORIAS FORA DO ESTADO', NULL, NULL);
INSERT INTO `cfops` VALUES (700, 7951, 'VENDA DE MERCADORIA FORA DO ESTAD.', NULL, NULL);
INSERT INTO `cfops` VALUES (701, 7952, 'DEVOLUÇÃO', NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
